### ISSUE TITLE
Rename 'Install Bioconductor' to 'Install BiocManager'

### ISSUE THREAD

**Issue by mtmorgan** [Bioconductor/BiocAddins#1]
Here

https://github.com/Bioconductor/BiocAddins/blob/f11a45d6cca7eefdc1e20e74e1b11a4bab7d5196/inst/rstudio/addins.dcf#L1

the add-in is labelled 'Install Bioconductor' but one actually gets BiocManager (and the ability to install additional Bioconductor packages) rather than all-of-Bioconductor.

**Comment by LiNk-NY** [comment]
Hi Martin, @mtmorgan 
Thanks for taking a look at these.

Bioconductor addins are targeted for novice users who likely know little to nothing about BiocManager. I thought that 'Install Bioconductor' made more sense for those new to Bioconductor.

In addition, Bioconductor can take on different meanings, not necessarily the entire
suite of packages.
I will update the name and provide more information in the description. 
Thanks.
